version: "3"
services:

  rpi-monitor:
    image: michaelmiklis/rpi-monitor
    container_name: rpi-monitor
    volumes:
      - /opt/vc:/opt/vc
      - /boot:/boot
      - /sys:/dockerhost/sys:ro
      - /etc:/dockerhost/etc:ro
      - /proc:/dockerhost/proc:ro
      - /usr/lib:/dockerhost/usr/lib:ro
    devices:
      - "/dev/vchiq:/dev/vchiq" 
      - "/dev/vcsm-cma:/dev/vcsm"  
    ports:
      - 8888:8888
    logging:
      driver: none
    #restart: unless-stopped
  
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /mnt:/mnt
      - plex_data:/config
    ports:
      - 32400:32400
    logging:
      driver: none
    #restart: unless-stopped
  
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kyiv
    volumes:
      - /mnt:/mnt
      - transmission_data:/config
      - ./transmission/settings.json:/var/lib/transmission-daemon/info/settings.json:ro
      - ./transmission/settings.json:/defaults/settings.json:ro
      - ./transmission/settings.json:/config/settings.json:ro
    ports:
      - 9091:9091
      - 49153:49153
      - 49153:49153/udp
    logging:
      driver: none
    #restart: unless-stopped
  
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kyiv
    volumes:
      - jackett_data:/config
      - /mnt/Samsung_T5/:/downloads
    ports:
      - 9117:9117
    logging:
      driver: none
    #restart: unless-stopped
  
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EEST
    volumes:
      - sonarr_data:/config
      - /mnt:/mnt
    ports:
      - 8989:8989
    logging:
      driver: none
    #restart: unless-stopped
  
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EEST
    volumes:
      - radarr_data:/config
      - /mnt:/mnt
    ports:
      - 7878:7878
    logging:
      driver: none
    #restart: unless-stopped
    
volumes:
  plex_data:
  transmission_data:
  jackett_data:
  sonarr_data:
  radarr_data:
