version: "3"
services:

  rpi-monitor:
    image: chrborg/rpi-monitor:latest
    container_name: rpi-monitor
    environment:
      - TZ=Europe/Kiev
    volumes:
      - /opt/vc:/opt/vc
      - /boot:/boot
      - /sys:/dockerhost/sys:ro
      - /etc:/dockerhost/etc:ro
      - /proc:/dockerhost/proc:ro
      - /usr/lib:/dockerhost/usr/lib:ro
      - /mnt/Samsung_T5:/mnt/Samsung_T5:ro
      - ./rpi-monitor/templates/usb_hdd.conf:/etc/rpimonitor/template/usb_hdd.conf
    devices:
      - "/dev/vchiq:/dev/vchiq"
      - "/dev/vcsm-cma:/dev/vcsm"
      - "/dev/sda1:/dev/sda1"
    ports:
      - 8888:8888
    logging:
      driver: none
    #restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=Europe/Kiev
    volumes:
      - plex_data:/config
      - /mnt:/mnt
    ports:
      - 32400:32400
    logging:
      driver: none
    #restart: unless-stopped

  #jellyfin:
  #  image: jellyfin/jellyfin:latest
  #  container_name: jellyfin
  #  network_mode: host
  #  user: 1000:1000
  #  volumes:
  #    - jellyfin_config:/config
  #    - jellyfin_cache:/cache
  #    - /mnt/Samsung_T5/Movies:/media/Movies
  #    - /mnt/Samsung_T5/TV Shows:/media/TV Shows
  #logging:
  #  driver: none
  #restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kyiv
    volumes:
      - transmission_data:/config
      - /mnt:/mnt
      - ./transmission/settings.json:/var/lib/transmission-daemon/info/settings.json:ro
      - ./transmission/settings.json:/defaults/settings.json:ro
      - ./transmission/settings.json:/config/settings.json:ro
    ports:
      - 9091:9091
      - 49153:49153
      - 49153:49153/udp
    logging:
      driver: none
    #restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - jackett_data:/config
      - /mnt/Samsung_T5/:/downloads
    ports:
      - 9117:9117
    logging:
      driver: none
    #restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - sonarr_data:/config
      - /mnt:/mnt
    ports:
      - 8989:8989
    logging:
      driver: none
    #restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - radarr_data:/config
      - /mnt:/mnt
    ports:
      - 7878:7878
    logging:
      driver: none
    #restart: unless-stopped

  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - file_browser_data:/database
      - /mnt:/srv
    ports:
      - 8080:80
    logging:
      driver: none
    #restart: unless-stopped

  minidlna:
    image: vladgh/minidlna
    container_name: minidlna
    volumes:
      - /mnt/:/media
    network_mode: host
    environment:
      TZ: Europe/Kiev
      MINIDLNA_MEDIA_DIR_1: "/media/Samsung_T5/Movies"
      MINIDLNA_MEDIA_DIR_2: "/media/Samsung_T5/TV Shows"
      MINIDLNA_FRIENDLY_NAME: "Raspberry Media Server"
    logging:
      driver: none
    #restart: unless-stopped

  samba:
    image: dperson/samba
    container_name: samba
    deploy:
      resources:
        limits:
          memory: 512m
    environment:
      TZ: Europe/Kiev
      USERID: 1000
      GROUPID: 1000
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - /mnt:/media
    command: '-s "Movies;/media/Samsung_T5/Movies;yes;no;yes;" -s "TV_Shows;/media/Samsung_T5/TV\ Shows;yes;no;yes;" -p'
    logging:
      driver: none
    #restart: unless-stopped

volumes:
  plex_data:
  transmission_data:
  jackett_data:
  sonarr_data:
  radarr_data:
  file_browser_data:
  jellyfin_cache:
  jellyfin_config:
