version: "2.4"
services:

  rpi-monitor:
    image: chrborg/rpi-monitor:latest
    container_name: rpi-monitor
    environment:
      - TZ=Europe/Kiev
    volumes:
      - /opt/vc:/opt/vc
      - /boot:/boot
      - /sys:/dockerhost/sys:ro
      - /etc:/dockerhost/etc:ro
      - /proc:/dockerhost/proc:ro
      - /usr/lib:/dockerhost/usr/lib:ro
      - /mnt/Seagate8TB:/mnt/Seagate8TB:ro
      - ./rpi-monitor/templates/usb_hdd.conf:/etc/rpimonitor/template/usb_hdd.conf
    devices:
      - "/dev/vchiq:/dev/vchiq"
      - "/dev/vcsm-cma:/dev/vcsm"
      - "/dev/sda2:/dev/sda2"
    ports:
      - 8888:8888
    logging:
      driver: none
    #restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=Europe/Kiev
    volumes:
      - plex_data:/config
      - /mnt:/mnt
    ports:
      - 32400:32400
    logging:
      driver: none
    #restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kyiv
    volumes:
      - transmission_data:/config
      - /mnt:/mnt
      - ./transmission/settings.json:/var/lib/transmission-daemon/info/settings.json:ro
      - ./transmission/settings.json:/defaults/settings.json:ro
      - ./transmission/settings.json:/config/settings.json:ro
    ports:
      - 9091:9091
      - 49153:49153
      - 49153:49153/udp
    logging:
      driver: none
    cpus: 2
    #restart: unless-stopped

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kyiv
    volumes:
      - deluge_data:/config
      - /mnt/Seagate8TB/Downloads:/downloads
      - /mnt/Seagate8TB:/mnt/Seagate8TB
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846
    cpus: 2
    #restart: unless-stopped

  deluge-ui:
    image: ghcr.io/relvacode/storm
    container_name: deluge-ui
    environment:
      - DELUGE_RPC_VERSION=v2
      - DELUGE_RPC_HOSTNAME=deluge
      - DELUGE_RPC_PORT=58846
      - DELUGE_RPC_USERNAME=localclient
      - DELUGE_RPC_PASSWORD=109c05537b4c56a3a19cda5436e27348df923d87
    ports:
      - 8221:8221
    #restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - jackett_data:/config
      - /mnt/Seagate8TB/:/downloads
    ports:
      - 9117:9117
    logging:
      driver: none
    #restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - sonarr_data:/config
      - /mnt:/mnt
    ports:
      - 8989:8989
    logging:
      driver: none
    #restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - radarr_data:/config
      - /mnt:/mnt
    ports:
      - 7878:7878
    logging:
      driver: none
    #restart: unless-stopped

  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
      - FB_NOAUTH=true
    volumes:
      - file_browser_data:/database
      - /mnt:/srv
    ports:
      - 8080:80
    logging:
      driver: none
    #restart: unless-stopped

  minidlna:
    image: vladgh/minidlna
    container_name: minidlna
    volumes:
      - /mnt:/media
    network_mode: host
    environment:
      TZ: Europe/Kiev
      MINIDLNA_MEDIA_DIR_1: "/media/Seagate8TB/Movies"
      MINIDLNA_MEDIA_DIR_2: "/media/Seagate8TB/Shows"
      MINIDLNA_FRIENDLY_NAME: "Raspberry Media Server"
    logging:
      driver: none
    #restart: unless-stopped

  samba:
    image: dperson/samba
    container_name: samba
    deploy:
      resources:
        limits:
          memory: 512m
    environment:
      TZ: Europe/Kiev
      USERID: 1000
      GROUPID: 1000
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - /mnt:/media
    command: '-s "Movies;/media/Seagate8TB/Movies;yes;no;yes;" -s "Shows;/media/Seagate8TB/Shows;yes;no;yes;" -p'
    logging:
      driver: none
    #restart: unless-stopped

volumes:
  plex_data:
  transmission_data:
  jackett_data:
  sonarr_data:
  radarr_data:
  file_browser_data:
  deluge_data:
