version: "2.4"
services:

  rpi-monitor:
    image: chrborg/rpi-monitor:latest
    container_name: rpi-monitor
    environment:
      - TZ=Europe/Kiev
    volumes:
      - /opt/vc:/opt/vc
      - /boot:/boot
      - /sys:/dockerhost/sys:ro
      - /etc:/dockerhost/etc:ro
      - /proc:/dockerhost/proc:ro
      - /usr/lib:/dockerhost/usr/lib:ro
      - /mnt/Seagate8TB:/mnt/Seagate8TB:ro
      - ./rpi-monitor/templates/usb_hdd.conf:/etc/rpimonitor/template/usb_hdd.conf
      - ./rpi-monitor/templates/version.conf:/etc/rpimonitor/template/version.conf
    devices:
      - "/dev/vchiq:/dev/vchiq"
      - "/dev/vcsm-cma:/dev/vcsm"
      - "/dev/sda2:/dev/sda2"
    ports:
      - 8888:8888
    logging:
      options:
        max-size: "1m"
        max-file: "10"
    healthcheck:
      disable: true
    #restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=Europe/Kiev
    volumes:
      - plex_data:/config
      - /mnt:/mnt
    ports:
      - 32400:32400
    healthcheck:
      disable: true
    logging:
      options:
        max-size: "1m"
        max-file: "10"
    #restart: unless-stopped

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kyiv
    volumes:
      - transmission_data:/config
      - /mnt:/mnt
      - ./transmission/settings.json:/var/lib/transmission-daemon/info/settings.json:ro
      - ./transmission/settings.json:/defaults/settings.json:ro
      - ./transmission/settings.json:/config/settings.json:ro
      #- ./transmission/transmissionic:/usr/share/transmission/public_html
    ports:
      - 9091:9091
      - 49153:49153
      - 49153:49153/udp
    logging:
      options:
        max-size: "1m"
        max-file: "10"
    healthcheck:
      disable: true
    cpus: 2
    #restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - jackett_data:/config
      - /mnt/Seagate8TB/:/downloads
    ports:
      - 9117:9117
    healthcheck:
      disable: true
    logging:
      options:
        max-size: "1m"
        max-file: "10"
    #restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - sonarr_data:/config
      - /mnt:/mnt
    ports:
      - 8989:8989
    healthcheck:
      disable: true
    logging:
      options:
        max-size: "1m"
        max-file: "10"
    #restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - radarr_data:/config
      - /mnt:/mnt
    ports:
      - 7878:7878
    healthcheck:
      disable: true
    logging:
      options:
        max-size: "1m"
        max-file: "10"
    #restart: unless-stopped

  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
      - FB_NOAUTH=true
    volumes:
      - file_browser_data:/database
      - /mnt:/srv
    ports:
      - 8080:80
    healthcheck:
      disable: true
    logging:
      options:
        max-size: "1m"
        max-file: "10"
    #restart: unless-stopped

  minidlna:
    image: vladgh/minidlna
    container_name: minidlna
    volumes:
      - /mnt:/media
    network_mode: host
    environment:
      TZ: Europe/Kiev
      MINIDLNA_MEDIA_DIR_1: "/media/Seagate8TB/Movies"
      MINIDLNA_MEDIA_DIR_2: "/media/Seagate8TB/Shows"
      MINIDLNA_FRIENDLY_NAME: "Raspberry Media Server"
    healthcheck:
      disable: true
    logging:
      options:
        max-size: "1m"
        max-file: "10"
    #restart: unless-stopped

  samba:
    image: dperson/samba
    container_name: samba
    environment:
      TZ: Europe/Kiev
      USERID: 1000
      GROUPID: 1000
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - /mnt:/media
    command: '-s "Movies;/media/Seagate8TB/Movies;yes;no;yes;" -s "Shows;/media/Seagate8TB/Shows;yes;no;yes;" -s "Reads;/media/Seagate8TB/Reads;yes;no;yes;" -p'
    healthcheck:
      disable: true
    logging:
      options:
        max-size: "1m"
        max-file: "10"
    #restart: unless-stopped

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - homeassistant_data:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    #  - ./home-assistant/custom_components/prana:/config/custom_components/prana
    privileged: true
    network_mode: host
    logging:
      driver: json-file
      options:
        max-size: "1mb"
        max-file: "10"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    healthcheck:
      disable: true
    logging:
      options:
        max-size: "1m"
        max-file: "10"

#  kavita:
#    image: jvmilazz0/kavita:latest
#    container_name: kavita
#    volumes:
#      - /mnt/Seagate8TB/Reads/Manga:/manga
#      - /mnt/Seagate8TB/Reads/Books:/books
#      - kavita_data:/kavita/config
#    ports:
#      - 5000:5000
#    healthcheck:
#      disable: true
#    logging:
#      options:
#        max-size: "1m"
#        max-file: "10"

#  kavita-proxy:
#    image: decentralize/caching-proxy
#    container_name: kavita-proxy
#    environment:
#      UPSTREAM: http://kavita:5000
#      MAX_SIZE: 500m
#      PROXY_CACHE_VALID: 10m
#    ports:
#      - 5555:80/tcp
#    logging:
#      options:
#        max-size: "1m"
#        max-file: "10"

  # prana_rc:
  #   build:
  #     context: .
  #     dockerfile: prana/Dockerfile
  #   container_name: prana_rc
  #   ports:
  #     - 8881:8881
  #   volumes:
  #     - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
  #   healthcheck:
  #     disable: true
  #   logging:
  #     options:
  #       max-size: "1m"
  #       max-file: "10"

volumes:
  plex_data:
  transmission_data:
  jackett_data:
  sonarr_data:
  radarr_data:
  file_browser_data:
  portainer_data:
  homebridge_data:
  homeassistant_data:
  kavita_data:
